name: Terraform

on:
  push:
    branches: [ Entrega13 ]
  pull_request:
    branches: [ Entrega13 ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: ./Proyecto
        run: terraform init

      - name: Terraform Validate
        working-directory: ./Proyecto
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./Proyecto
        run: terraform plan -no-color

      - name: Terraform Apply
        if: github.ref == 'refs/heads/Entrega13'
        working-directory: ./Proyecto
        run: terraform apply -auto-approve -no-color
